# Generated by Django 3.2.11 on 2023-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectmedia')),
                ('output', models.CharField(blank=True, max_length=300, null=True)),
                ('predicted_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=1000)),
                ('disease_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='image',
            field=models.ImageField(upload_to='projectmedia'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('history', models.ManyToManyField(blank=True, to='predicition.Predictions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrecautionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cure_text', models.CharField(max_length=2000)),
                ('refrences', models.ManyToManyField(to='predicition.Refrences')),
            ],
        ),
    ]
