# Generated by Django 3.2.11 on 2023-05-12 18:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicition', '0002_auto_20230512_1937'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='predicted_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
